let TechKaro = [
    {
        Founder: "Sadafee"
    },
    {
        mission: ["Women impowerment", "Program for Women"],

    },
    {
        Branch: 5
    },
    {
        Faculty: ["Miss Sarah", "Miss Tuba"]
    },
    {
        Course: "Web_Development"
    },
    {
        Student:[
            {
            Name: "Oliver",
            Father_Name: "Charlie",
            Mother_Name: "Mahnoor",
            DOB: "12/01/1990",
            Education: "BCom",
            Nic: 423022344,
            Email: "abc123@gmail.com",
            Contact: 0320123,
            Father_income: 2000,
            Personal_income: 3400,
            isEmployed: true,
            Address: "gulshan",
        },
        {
            Name: "rthur",
            Father_Name: "Charlie",
            Mother_Name:"Mahnoor" ,
            DOB: "12/01/1991",
            Education: "BCom",
            Nic: 423022344,
            Email: "abc123@gmail.com",
            Contact: 0320123,
            Father_income: 2000,
            Personal_income:3400,
            isEmployed: true,
            Address: "Haded",
        },
        {
            Name: "Oliver",
            Father_Name: "rthur",
            Mother_Name: "Mahnoor",
            DOB: "12/01/1992",
            Education: "BCom",
            Nic: 423022344,
            Email: "abc123@gmail.com",
            Contact: 0320123,
            Father_income: 2000,
            Personal_income: 3400,
            isEmployed: true,
            Address: "gulshan"
        },
        {
            Name: "Henry",
            Father_Name: "Oliver",
            Mother_Name: "Mahnoor",
            DOB: "12/01/1993",
            Education: "BCom",
            Nic: 423022344,
            Email: "abc123@gmail.com",
            Contact: 0320123,
            Father_income: 2000,
            Personal_income: 3400,
            isEmployed: true,
            Address: "Haded"
        },
        {
            Name: "Oliver",
            Father_Name: "Henry",
            Mother_Name: "Mahnoor",
            DOB: "12/01/1994",
            Education: "BCom",
            Nic: 423022344,
            Email: "abc123@gmail.com",
            Contact: 0320123,
            Father_income: 2000,
            Personal_income:3400,
            isEmployed: true,
            Address: "Haded"
        },
        {
            Name:"Oliver",
            Father_Name: "Henry",
            Mother_Name: "Mahnoor",
            DOB: "12/01/1995",
            Education: "BCom",
            Nic: 423022344,
            Email: "abc123@gmail.com",
            Contact: 0320123,
            Father_income: 2000,
            Personal_income: 3400,
            isEmployed: true,
            Address: "gulshan"
        },
        {
            Name: "Aaron",
            Father_Name: "Henry",
            Mother_Name: "Neha",
            DOB: "12/01/1996",
            Education: "BCom",
            Nic: 423022344,
            Email: "abc123@gmail.com",
            Contact: 0320123,
            Father_income: 2000,
            Personal_income: 3400,
            isEmployed: true,
            Address: "Haded"
        },
        {
            Name: "Aaron",
            Father_Name: "Fedrik",
            Mother_Name: "Henry",
            DOB: "12/01/1997",
            Education: "BCom",
            Nic: 423022344,
            Email: "abc123@gmail.com",
            Contact: 0320123,
            Father_income: 2000,
            Personal_income: 3400,
            isEmployed: true,
            Address: "gulshan"
        },
        {
            Name: "Aaron",
            Father_Name: "rthur",
            Mother_Name: "Neha",
            DOB: "12/01/1998",
            Education: "BCom",
            Nic: 423022344,
            Email: "abc123@gmail.com",
            Contact: 0320123,
            Father_income: 2000,
            Personal_income: 3400,
            isEmployed: true,
            Address: "Haded"
        },
        {
            Name: "Aaron",
            Father_Name: "Andrew",
            Mother_Name: "Henry",
            DOB: "12/01/1999",
            Education: "BCom",
            Nic: 423022344,
            Email: "abc123@gmail.com",
            Contact: 0320123,
            Father_income: 2000,
            Personal_income: 3400,
            isEmployed: true,
            Address: "gulshan"
        },
        {
            Name: "Aaron",
            Father_Name: "Charlie",
            Mother_Name: "Oliver",
            DOB: "12/01/1990",
            Education: "BCom",
            Nic: 423022344,
            Email: "abc123@gmail.com",
            Contact: 0320123,
            Father_income: 2000,
            Personal_income: 3400,
            isEmployed: true,
            Address: "Haded"
        },
        {
            Name: "Aaron",
            Father_Name: "Henry",
            Mother_Name: "Neha",
            DOB: "12/01/1991",
            Education: "BCom",
            Nic: 423022344,
            Email: "abc123@gmail.com",
            Contact: 0320123,
            Father_income: 2000,
            Personal_income:3400,
            isEmployed: true,
            Address: "gulshan"
        },
        {
            Name: "Aaron",
            Father_Name: "Henry",
            Mother_Name: "Neha",
            DOB: "12/01/1990",
            Education: "BCom",
            Nic: 423022344,
            Email: "abc123@gmail.com",
            Contact: 0320123,
            Father_income: 2000,
            Personal_income: 3400,
            isEmployed: true,
            Address: "Haded"
        },
        {
            Name: "Aaron",
            Father_Name: "Oliver",
            Mother_Name: "Neha",
            DOB: "12/01/1997",
            Education: "BCom",
            Nic: 423022344,
            Email: "abc123@gmail.com",
            Contact: 0320123,
            Father_income: 2000,
            Personal_income: 3400,
            isEmployed: true,
            Address: "gulshan"
        },
        {
            Name: "Aaron",
            Father_Name: "Henry",
            Mother_Name: "Neha",
            DOB: "12/01/1995",
            Education: "BCom",
            Nic: 423022344,
            Email: "abc123@gmail.com",
            Contact: 0320123,
            Father_income: 2000,
            Personal_income:3400,
            isEmployed: true,
            Address: "gulshan"
        },
        {
            Name: "Aaron",
            Father_Name: "rthur",
            Mother_Name: "Olivia",
            DOB: "12/01/1995",
            Education: "BCom",
            Nic: 423022344,
            Email: "abc123@gmail.com",
            Contact: 0320123,
            Father_income: 2000,
            Personal_income: 1500,
            isEmployed: true,
            Address: "Haded"
        },
        {
            Name: "Aaron",
            Father_Name: "Henry",
            Mother_Name: "Neha",
            DOB: "12/01/1996",
            Education: "BCom",
            Nic: 423022344,
            Email: "abc123@gmail.com",
            Contact: 0320123,
            Father_income: 2000,
            Personal_income: 1500,
            isEmployed: true,
            Address: "gulshan"
        },
        {
            Name: "Aaron",
            Father_Name: "Andrew",
            Mother_Name: "Charlie",
            DOB: "12/01/1990",
            Education: "BCom",
            Nic: 423022344,
            Email: "abc123@gmail.com",
            Contact: 0320123,
            Father_income: 2000,
            Personal_income:1500,
            isEmployed: true,
            Address: "Haded"
        },
        {
            Name: "Aaron",
            Father_Name: "Freddie",
            Mother_Name: "Henry",
            DOB: "12/01/1999",
            Education: "BCom",
            Nic: 423022344,
            Email: "abc123@gmail.com",
            Contact: 0320123,
            Father_income: 2000,
            Personal_income:1500,
            isEmployed: true,
            Address: "gulshan"
        },
        {
            Name: "Aaron",
            Father_Name: "James",
            Mother_Name: "Neha",
            DOB: "12/01/1993",
            Education: "BCom",
            Nic: 423022344,
            Email: "abc123@gmail.com",
            Contact: 0320123,
            Father_income: 2000,
            Personal_income: 1500,
            isEmployed: true,
            Address: "Haded"
        },
        {
            Name: "Aaron",
            Father_Name: "James",
            Mother_Name: "Neha",
            DOB: "12/01/1998",
            Education: "BCom",
            Nic: 423022344,
            Email: "abc123@gmail.com",
            Contact: 0320123,
            Father_income: 2000,
            Personal_income: 1500,
            isEmployed: true,
            Address: "gulshan"
        },
        {
            Name: "Aaron",
            Father_Name: "James",
            Mother_Name: "Neha",
            DOB: "12/01/1991",
            Education: "d",
            Nic: 1,
            Email: "q",
            Contact: 2,
            Father_income: "xx",
            Personal_income: 1500,
            isEmployed: true,
            Address: "gul"
        },
        {
            Name: "Aaron",
            Father_Name: "James",
            Mother_Name: "Neha",
            DOB: "12/01/1995",
            Education: "BCom",
            Nic: 423022344,
            Email: "abc123@gmail.com",
            Contact: 0320123,
            Father_income: 2000,
            Personal_income:1500,
            isEmployed: true,
            Address: "gulshan"
        },
        {
            Name: "Aaron",
            Father_Name: "Freddie",
            Mother_Name: "Neha",
            DOB: "12/01/1991",
            Education: "BCom",
            Nic: 423022344,
            Email: "abc123@gmail.com",
            Contact: 0320123,
            Father_income: 2000,
            Personal_income: 1500,
            isEmployed: true,
            Address: "Saddar"
        },
        {
            Name: "Aaron",
            Father_Name: "Anthony",
            Mother_Name: "James",
            DOB: "12/01/1999",
            Education: "BCom",
            Nic: 423022344,
            Email: "abc123@gmail.com",
            Contact: 0320123,
            Father_income: 2000,
            Personal_income: 1500,
            isEmployed: true,
            Address: "Saddar"
        },
        {
            Name: "Aaron",
            Father_Name: "James",
            Mother_Name: "Neha",
            DOB: "12/01/1993",
            Education: "BCom",
            Nic: 423022344,
            Email: "abc123@gmail.com",
            Contact: 0320123,
            Father_income: 2000,
            Personal_income: 1500,
            isEmployed: true,
            Address: "gulshan"
        },
        {
            Name: "Freddie",
            Father_Name: "arthur",
            Mother_Name: "Neha",
            DOB: "12/01/1990",
            Education: "BCom",
            Nic: 423022344,
            Email: "abc123@gmail.com",
            Contact: 0320123,
            Father_income: 2000,
            Personal_income:1500,
            isEmployed: true,
            Address: "gulshan"
        },
        {
            Name: "Freddie",
            Father_Name: "James",
            Mother_Name: "Neha",
            DOB: "12/01/1990",
            Education: "BCom",
            Nic: 423022344,
            Email: "abc123@gmail.com",
            Contact: 0320123,
            Father_income: 2000,
            Personal_income:1500,
            isEmployed: true,
            Address: "Saddar"
        },
        {
            Name: "Freddie",
            Father_Name: "James",
            Mother_Name: "Neha",
            DOB: "12/01/1990",
            Education: "BCom",
            Nic: 423022344,
            Email: "abc123@gmail.com",
            Contact: 0320123,
            Father_income: 2000,
            Personal_income: 1500,
            isEmployed: true,
            Address: "gulshan"
        },
        {
            Name: "Edward",
            Father_Name: "arthur",
            Mother_Name: "Neha",
            DOB: "12/01/1990",
            Education: "BCom",
            Nic: 423022344,
            Email: "abc123@gmail.com",
            Contact: 0320123,
            Father_income: 2000,
            Personal_income: 1500,
            isEmployed: true,
            Address: "Saddar"
        },
        {
            Name: "Freddie",
            Father_Name: "James",
            Mother_Name: "Neha",
            DOB: "12/01/1990",
            Education: "BCom",
            Nic: 423022344,
            Email: "abc123@gmail.com",
            Contact: 0320123,
            Father_income: 2000,
            Personal_income: 1500,
            isEmployed: true,
            Address: "gulshan"
        },
        {
            Name: "Freddie",
            Father_Name: "Edward",
            Mother_Name: "Neha",
            DOB: "12/01/1990",
            Education: "BCom",
            Nic: 423022344,
            Email: "abc123@gmail.com",
            Contact: 0320123,
            Father_income: 2000,
            Personal_income:1500,
            isEmployed: true,
            Address: "Saddar"
        },
        {
            Name: "James",
            Father_Name: "Freddie",
            Mother_Name: "Neha",
            DOB: "12/01/1989",
            Education: "BCom",
            Nic: 423022344,
            Email: "abc123@gmail.com",
            Contact: 0320123,
            Father_income: 2000,
            Personal_income: 1500,
            isEmployed: true,
            Address: "gulshan"
        },
        {
            Name: "Freddie",
            Father_Name: "Edward",
            Mother_Name: "Neha",
            DOB: "12/01/1990",
            Education: "BCom",
            Nic: 423022344,
            Email: "abc123@gmail.com",
            Contact: 0320123,
            Father_income: 2000,
            Personal_income: 1500,
            isEmployed: true,
            Address: "Saddar"
        },
        {
            Name: "Freddie",
            Father_Name: "Charlie",
            Mother_Name: "Neha",
            DOB: "12/01/1990",
            Education: "BCom",
            Nic: 423022344,
            Email: "abc123@gmail.com",
            Contact: 0320123,
            Father_income: 2000,
            Personal_income: 1500,
            isEmployed: true,
            Address: "gulshan"
        }
        ]
    },
    {
        Tech_Ninja: ["Ali", "Noreen_Naz","Edward"]
    },
    {
        Mentor: ["ABC", "XYZ"]
    }
];